### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by emergencyd** [aherbert/GDSC-SMLM#1]
I got the error below:
`Results :

Failed tests:   floatBlockFindNxNInternalIsFasterThanBlockFindNxNForBigBorders(gdsc.core.filters.NonMaximumSuppressionTest): Internal not faster: 198927756 > 168602366
  canComputeConvexHullFromSquare(gdsc.core.utils.ConvexHullTest): expected:<0.0> but was:<10.0>
  canComputeConvexHullFromSquareWithInternalPoint(gdsc.core.utils.ConvexHullTest): expected:<0.0> but was:<10.0>
  canComputeConvexHullFromSquareWithInternalPoint2(gdsc.core.utils.ConvexHullTest): expected:<0.0> but was:<10.0>
  floatVersionIsFasterThanDoubleVersion(gdsc.core.utils.MedianWindowTest): Radius 64, Increment 8
  testClassCanComputeActualMedian(gdsc.core.utils.MedianWindowTest): Position 0, Radius 0 expected:<NaN> but was:<1233.7313232421875>
  isFasterThenMedianWindowUsingSortedCacheData(gdsc.core.utils.MedianWindowDLLTest): Radius 64, Increment 32
  pairwiseWithoutNeighboursIsFasterAtLowDensities(gdsc.core.clustering.ClusteringEngineTest)

Tests run: 220, Failures: 8, Errors: 0, Skipped: 4

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:56.487s
[INFO] Finished at: Mon Mar 20 16:20:02 EDT 2017
[INFO] Final Memory: 28M/325M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project gdsc-core: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/shujian/Downloads/GDSC-Core/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

**Comment by aherbert** [comment]
Some of the tests are speed tests for similar algorithms. Due to the use of random number seeds and also the spin up of the JVM, sometimes slower algorithms test faster than expected and the test fails. Don't worry about it and just build with the maven flag -D skipTests. The skip test flag is recommended in the README.md. The build is really slow with all the tests anyway as some do a full super resolution simulations for testing PC PALM or diffusion analysis.

I will change the tests in the future to be optional.

Alex

On 20 Mar 2017 20:24, emergencyd <notifications@github.com> wrote:

I got the error below:
`Results :

Failed tests: floatBlockFindNxNInternalIsFasterThanBlockFindNxNForBigBorders(gdsc.core.filters.NonMaximumSuppressionTest): Internal not faster: 198927756 > 168602366
canComputeConvexHullFromSquare(gdsc.core.utils.ConvexHullTest): expected:<0.0> but was:<10.0>
canComputeConvexHullFromSquareWithInternalPoint(gdsc.core.utils.ConvexHullTest): expected:<0.0> but was:<10.0>
canComputeConvexHullFromSquareWithInternalPoint2(gdsc.core.utils.ConvexHullTest): expected:<0.0> but was:<10.0>
floatVersionIsFasterThanDoubleVersion(gdsc.core.utils.MedianWindowTest): Radius 64, Increment 8
testClassCanComputeActualMedian(gdsc.core.utils.MedianWindowTest): Position 0, Radius 0 expected: but was:<1233.7313232421875>
isFasterThenMedianWindowUsingSortedCacheData(gdsc.core.utils.MedianWindowDLLTest): Radius 64, Increment 32
pairwiseWithoutNeighboursIsFasterAtLowDensities(gdsc.core.clustering.ClusteringEngineTest)

Tests run: 220, Failures: 8, Errors: 0, Skipped: 4

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:56.487s
[INFO] Finished at: Mon Mar 20 16:20:02 EDT 2017
[INFO] Final Memory: 28M/325M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project gdsc-core: There are test failures.
[ERROR]
[ERROR] Please refer to /home/shujian/Downloads/GDSC-Core/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

**Comment by aherbert** [comment]
The failing tests have been fixed. These were due to a change in Apache Commons Math.

The failing speed tests have been made optional since they are sensitive to the current code optimisation within the JVM.

The recommended way to build ignoring tests is:

> mvn -P dist package -DskipTests=true
